### ISSUE TITLE
Tests are failing because of missing libheif

### ISSUE THREAD

**Issue by janaagaard75** [vseventer/sharp-cli#33]
I get 7 errors when i run `npm test`. They all seems related to `libheif` being missing. Is there any way I can fix this? I am trying to create a pull request where `sharp` is updated to the latest v0.24.0, because that solves https://github.com/expo/expo-cli/issues/1373.

     Error: The heif operation requires libvips to have been installed with support for libheif
     AssertionError: ["webp"] must have length of 2
     AssertError: expected heif to be called with match 
     AssertionError: ["webp","tiff","jpeg"] must have length of 4
     AssertError: expected heif to be called with match 
     AssertionError: ["webp","tiff","jpeg"] must have length of 4
     AssertError: expected heif to be called with match 

### Full error log

```
  1) sharp-cli <options> [command..]
       <options>
         --hcompression
           must execute the pipeline:
     Error: The heif operation requires libvips to have been installed with support for libheif
      at Sharp.heif (node_modules/sharp/lib/output.js:456:11)
      at Function.invoke (node_modules/sinon/lib/sinon/spy.js:302:51)
      at Sharp.heif (node_modules/sinon/lib/sinon/spy.js:90:30)
      at /Users/janaagaard/Projects/sharp-cli/lib/cli.js:83:305
      at /Users/janaagaard/Projects/sharp-cli/lib/queue.js:26:154
      at Array.reduce (<anonymous>)
      at Array.value (lib/queue.js:26:84)
      at Context.<anonymous> (test/cli.js:263:32)
      at /Users/janaagaard/Projects/sharp-cli/lib/cli.js:91:31
      at parse (node_modules/yargs/yargs.js:567:18)
      at Object.cli.parse (lib/cli.js:74:31)
      at Context.<anonymous> (test/cli.js:252:32)
      at processImmediate (internal/timers.js:456:21)

  2) sharp-cli <options> [command..]
       <options>
         --lossless
           must update the pipeline:
     AssertionError: ["webp"] must have length of 2
      at Context.<anonymous> (test/cli.js:320:40)
      at /Users/janaagaard/Projects/sharp-cli/lib/cli.js:91:31
      at parse (node_modules/yargs/yargs.js:567:18)
      at Object.cli.parse (lib/cli.js:74:31)
      at Context.<anonymous> (test/cli.js:313:32)
      at processImmediate (internal/timers.js:456:21)

  3) sharp-cli <options> [command..]
       <options>
         --lossless
           must execute the pipeline:
     AssertError: expected heif to be called with match 
      at Object.fail (node_modules/sinon/lib/sinon/assert.js:106:21)
      at failAssertion (node_modules/sinon/lib/sinon/assert.js:65:16)
      at Object.assert.<computed> [as calledWithMatch] (node_modules/sinon/lib/sinon/assert.js:91:13)
      at Context.<anonymous> (test/cli.js:326:22)
      at /Users/janaagaard/Projects/sharp-cli/lib/cli.js:91:31
      at parse (node_modules/yargs/yargs.js:567:18)
      at Object.cli.parse (lib/cli.js:74:31)
      at Context.<anonymous> (test/cli.js:313:32)
      at processImmediate (internal/timers.js:456:21)

  4) sharp-cli <options> [command..]
       <options>
         --q
           must update the pipeline:
     AssertionError: ["webp","tiff","jpeg"] must have length of 4
      at Context.<anonymous> (test/cli.js:538:42)
      at /Users/janaagaard/Projects/sharp-cli/lib/cli.js:91:31
      at parse (node_modules/yargs/yargs.js:567:18)
      at Object.cli.parse (lib/cli.js:74:31)
      at Context.<anonymous> (test/cli.js:531:34)
      at processImmediate (internal/timers.js:456:21)

  5) sharp-cli <options> [command..]
       <options>
         --q
           must execute the pipeline:
     AssertError: expected heif to be called with match 
      at Object.fail (node_modules/sinon/lib/sinon/assert.js:106:21)
      at failAssertion (node_modules/sinon/lib/sinon/assert.js:65:16)
      at Object.assert.<computed> [as calledWithMatch] (node_modules/sinon/lib/sinon/assert.js:91:13)
      at Context.<anonymous> (test/cli.js:546:24)
      at /Users/janaagaard/Projects/sharp-cli/lib/cli.js:91:31
      at parse (node_modules/yargs/yargs.js:567:18)
      at Object.cli.parse (lib/cli.js:74:31)
      at Context.<anonymous> (test/cli.js:531:34)
      at processImmediate (internal/timers.js:456:21)

  6) sharp-cli <options> [command..]
       <options>
         --quality
           must update the pipeline:
     AssertionError: ["webp","tiff","jpeg"] must have length of 4
      at Context.<anonymous> (test/cli.js:538:42)
      at /Users/janaagaard/Projects/sharp-cli/lib/cli.js:91:31
      at parse (node_modules/yargs/yargs.js:567:18)
      at Object.cli.parse (lib/cli.js:74:31)
      at Context.<anonymous> (test/cli.js:531:34)
      at processImmediate (internal/timers.js:456:21)

  7) sharp-cli <options> [command..]
       <options>
         --quality
           must execute the pipeline:
     AssertError: expected heif to be called with match 
      at Object.fail (node_modules/sinon/lib/sinon/assert.js:106:21)
      at failAssertion (node_modules/sinon/lib/sinon/assert.js:65:16)
      at Object.assert.<computed> [as calledWithMatch] (node_modules/sinon/lib/sinon/assert.js:91:13)
      at Context.<anonymous> (test/cli.js:546:24)
      at /Users/janaagaard/Projects/sharp-cli/lib/cli.js:91:31
      at parse (node_modules/yargs/yargs.js:567:18)
      at Object.cli.parse (lib/cli.js:74:31)
      at Context.<anonymous> (test/cli.js:531:34)
      at processImmediate (internal/timers.js:456:21)
```

**Comment by vseventer** [comment]
The tests cover all possible options, and therefore require you have installed `vips` compiled with `libheif` - see https://sharp.pixelplumbing.com/install#custom-libvips for instructions on how to do this.

**Comment by janaagaard75** [comment]
So I have to install a specially build binary of some global library in order to run the tests, right? I have to admit, that this is something that I would only want to do on a virtual machine.

**Comment by vseventer** [comment]
`libvips` is the underlying library used by sharp (and thus the CLI).

**Comment by janaagaard75** [comment]
Thanks for the quick response. I will close this and the other issue is created, and get back to you if I get the courage/time to make a pull request. Sorry for the inconvenience.
