### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by ManuCart** [vseventer/sharp-cli#4]
````
sharp --help
module.js:355
  Module._extensions[extension](this, filename);
                               ^

Error: Module version mismatch. Expected 46, got 48.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/sharp-cli/node_modules/sharp/index.js:12:13)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/sharp-cli/lib/runner.js:34:15)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)````

**Comment by vseventer** [comment]
This error pops up when you do `npm install`, but then change your node version (e.g. `nvm use`), without clearing your `node_modules/` and rerunning `npm install`.
