### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by blowsie** [vseventer/sharp-cli#6]
I'm getting an error when using the tool. Does the tool work on windows? 

```
λ sharp -i ./1.png -o ./out resize 300 200
C:\Users\sblowes\AppData\Roaming\npm\node_modules\sharp-cli\lib\index.js:35
module.exports = (argv, options = { }) => {
                                ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:54:16)
    at Module._compile (module.js:375:25)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (C:\Users\sblowes\AppData\Roaming\npm\node_modules\sharp-cli\bin\cli.js:29:1)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
```

**Comment by blowsie** [comment]
``
λ node -v
v5.2.0
```

**Comment by vseventer** [comment]
Required node version is 6 and up, that should do the trick.

**Comment by andrekosak** [comment]
Hello, i have one more question regarding Windows. I have Node 6 here, but i cannot manage how to use the cli properly. The point is, that it creates the new image in the same folder, and now uses the folder path i passed as "-o" parameter. See my output:

```
Admin@DESKTOP-RLI0V1T MINGW64 /d/Site/maerchen (master)
$ sharp -i ./static/images/* -o ./out resize 1500 0
D:%5CSite%5Cmaerchen%5Cout
D:%5CSite%5Cmaerchen%5Cout
```

So it's creating new files with wrong names.
I am using the "Git Bash" program. Because Powershell has another syntax of file path.

What do i do wrong?
