### ISSUE TITLE
Installation does not work on Manjaro

### ISSUE THREAD

**Issue by sveneberth** [vseventer/sharp-cli#89]
Hello,

I'm trying to install `sharp-cli`. But the installation always fails:

<details><summary>Log</summary>

```
npm install sharp-cli --verbose 
npm verb cli /usr/bin/node /usr/bin/npm
npm info using npm@10.3.0
npm info using node@v21.5.0
npm verb title npm install sharp-cli
npm verb argv "install" "sharp-cli" "--loglevel" "verbose"
npm verb logfile logs-max:10 dir:/home/sven/.npm/_logs/2024-01-23T14_24_58_087Z-
npm verb logfile /home/sven/.npm/_logs/2024-01-23T14_24_58_087Z-debug-0.log
npm http fetch GET 200 https://registry.npmjs.org/sharp-cli 14ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/bubble-stream-error 19ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/glob 20ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/lodash.pick 23ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/is-directory 24ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/sharp 24ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/yargs 27ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/inflight 32ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/once 35ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/inherits 34ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/sliced 36ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/minimatch 34ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/detect-libc 33ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/color 34ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/tar-fs 33ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/node-addon-api 35ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/once 39ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/simple-get 35ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/cliui 35ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/escalade 35ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/semver 37ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/prebuild-install 39ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/tunnel-agent 42ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/get-caller-file 41ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/require-directory 42ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/fs.realpath 50ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/string-width 44ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/yargs-parser 45ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/y18n 47ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/wrappy 3ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/brace-expansion 1ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/balanced-match 3ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/color-convert 26ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/color-string 26ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/minimist 22ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/github-from-package 23ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/napi-build-utils 23ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/expand-template 24ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/rc 22ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/pump 23ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/mkdirp-classic 25ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/node-abi 25ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/decompress-response 24ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/simple-concat 25ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/tar-stream 23ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/mkdirp-classic 25ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/lru-cache 28ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/safe-buffer 26ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/color-name 7ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/color-name 6ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/simple-swizzle 7ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/is-arrayish 1ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/deep-extend 10ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/end-of-stream 13ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/ini 11ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/chownr 10ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/strip-json-comments 12ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/yallist 2ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/mimic-response 3ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/fast-fifo 6ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/b4a 8ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/streamx 7ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/queue-tick 2ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/wrap-ansi 11ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/strip-ansi 13ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/emoji-regex 10ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/is-fullwidth-code-point 12ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/ansi-regex 5ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/ansi-styles 4ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/bl 4ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/fs-constants 5ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/readable-stream 5ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/buffer 7ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/string_decoder 7ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/util-deprecate 7ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/base64-js 3ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/ieee754 3ms (cache hit)
npm info run sharp@0.32.6 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm info run sharp@0.32.6 install { code: 7, signal: null }
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
npm verb stack     at ChildProcess.emit (node:events:519:28)
npm verb stack     at maybeClose (node:internal/child_process:1105:16)
npm verb stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
npm verb pkgid sharp@0.32.6
npm verb cwd /tmp/tmp.OPAhawkXzy
npm verb Linux 6.1.71-1-MANJARO
npm verb node v21.5.0
npm verb npm  v10.3.0
npm ERR! code 7
npm ERR! path /tmp/tmp.OPAhawkXzy/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm ERR! sharp: Detected globally-installed libvips v8.15.1
npm ERR! sharp: Building from source via node-gyp
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/bin/node',
npm ERR! gyp verb cli   '/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild'
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@21.5.0 | linux | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp ERR! UNCAUGHT EXCEPTION 
npm ERR! gyp ERR! stack Error: Cannot find module 'rimraf'
npm ERR! gyp ERR! stack Require stack:
npm ERR! gyp ERR! stack - /usr/lib/node_modules/npm/node_modules/node-gyp/lib/clean.js
npm ERR! gyp ERR! stack - /usr/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js
npm ERR! gyp ERR! stack - /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js
npm ERR! gyp ERR! stack     at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
npm ERR! gyp ERR! stack     at Module._load (node:internal/modules/cjs/loader:984:27)
npm ERR! gyp ERR! stack     at Module.require (node:internal/modules/cjs/loader:1234:19)
npm ERR! gyp ERR! stack     at require (node:internal/modules/helpers:176:18)
npm ERR! gyp ERR! stack     at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/clean.js:3:12)
npm ERR! gyp ERR! stack     at Module._compile (node:internal/modules/cjs/loader:1375:14)
npm ERR! gyp ERR! stack     at Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
npm ERR! gyp ERR! stack     at Module.load (node:internal/modules/cjs/loader:1206:32)
npm ERR! gyp ERR! stack     at Module._load (node:internal/modules/cjs/loader:1022:12)
npm ERR! gyp ERR! stack     at Module.require (node:internal/modules/cjs/loader:1234:19)
npm ERR! gyp ERR! System Linux 6.1.71-1-MANJARO
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /tmp/tmp.OPAhawkXzy/node_modules/sharp
npm ERR! gyp ERR! node -v v21.5.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! Node-gyp failed to build your package.
npm ERR! gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.
npm verb exit 7
npm verb unfinished npm timer reify 1706019898266
npm verb unfinished npm timer reify:build 1706019898812
npm verb unfinished npm timer build 1706019898813
npm verb unfinished npm timer build:deps 1706019898813
npm verb unfinished npm timer build:run:install 1706019898820
npm verb unfinished npm timer build:run:install:node_modules/sharp 1706019898820
npm verb code 7
```
</details> 

As you can see in the logs, I am using Manjaro Linux.
I have already tried `npm cache clean --force`, which did not bring any change. The installation of sharp itself `npm i sharp` works.

I am grateful for any tips.

**Comment by segun-flexible** [comment]
am facing same issues on Window 11 Home

**Comment by vseventer** [comment]
Closing due to inactivity.
